#!/bin/bash

CURRENT_DIR=${PWD}

echo $CURRENT_DIR


makey()
{
  make install -j8
}

buildCcache()
{
  echo "DESKTOP Cache"
  autoreconf --install &&  CXXFLAGS="-g -O0 --coverage" LDFLAGS="--coverage"  CXX="ccache g++" CC="ccache gcc" INSTALL="./install-sh -c -C" ./configure --prefix=$DESKTOP_PREFIX --enable-debug --enable-networklogging
}

buildGeneric()
{
  echo "DESKTOP generic"
  autoreconf --install &&  CXXFLAGS="-g -O0 --coverage" INSTALL="./install-sh -c -C" ./configure --prefix=$DESKTOP_PREFIX --enable-debug --enable-networklogging
}

cmakeSetup()
{
  cmake -DCMAKE_INSTALL_PREFIX=$DESKTOP_PREFIX -DCMAKE_BUILD_TYPE=Debug
}

build()
{
  echo "build for "

  case "$1" in

  1)  echo "Configure only generic"
      buildGeneric
      ;;
  2)  echo "Ccache"
      buildCcache && makey
      ;;
  *)  echo "Generic"
      buildGeneric && makey 
      ;;
  esac
}

buildCmake()
{
  case "$1" in

  1) echo "Cmake setup only"
     cmakeSetup
     ;;
  *) echo "Cmake setup and build"
     cmakeSetup && makey
     ;;
  esac
}

dali-core()
{
  echo "building dali core"
  cd $CURRENT_DIR/dali-core/build/tizen
  buildCmake $1
}

dali-adaptor()
{
  echo "building dali adaptor"
  cd $CURRENT_DIR/dali-adaptor/build/tizen
  buildCmake $1
}

dali-toolkit()
{
  echo "building dali toolkit"
  cd $CURRENT_DIR/dali-toolkit/build/tizen
  buildCmake $1
}

dali-csharp-binder()
{
  echo "building dali binder"
  cd $CURRENT_DIR/dali-csharp-binder/build/tizen
  buildCmake $1
}

dali-demo()
{
  echo "building dali demo"
  cd $CURRENT_DIR/dali-demo/build/tizen
 buildCmake $1 
}

dali-core $1 && dali-adaptor $1 && dali-toolkit $1 && dali-csharp-binder $1 && dali-demo $1



